development:
  adapter:  postgresql
  host:     localhost
  database: equibrief_dev
  pool: 5
  username: postgres

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: equibrief_prod
  pool: 5
  username: equibrief